### ISSUE TITLE
Data from France

### ISSUE THREAD

**Issue by jad-hamza** [mcyph/global_subnational_covid_data#1]
Hi,

That's a very nice and ambitious project!

I'm trying to use the data to visualize the evolution of the testing positivity rates in European subnational regions.

I have trouble understanding the data from France in this repo. This file https://github.com/mcyph/global_subnational_covid_data/blob/61aca8779fec173320bef02a2f2016cd3d21761f/casedata/fr/sante_publique/new.csv reports `1357` new cases for region `fr-13` and the date `2020-10-03`, and this one https://github.com/mcyph/global_subnational_covid_data/blob/61aca8779fec173320bef02a2f2016cd3d21761f/casedata/fr/sante_publique/tests_new.csv reports `14316` new tests for that region/day.

The official data from https://www.data.gouv.fr/fr/datasets/r/406c6a23-e283-4300-9484-54e78c8ae675 has the following lines for region (département) `13` and date `2020-10-03`:

```
13;2020-10-03;5;85;09
13;2020-10-03;22;219;19
13;2020-10-03;42;274;29
13;2020-10-03;23;258;39
13;2020-10-03;22;239;49
13;2020-10-03;30;220;59
13;2020-10-03;20;176;69
13;2020-10-03;9;146;79
13;2020-10-03;8;80;89
13;2020-10-03;7;37;90
13;2020-10-03;188;1734;0
```

The last row says the number of new cases for `2020-10-03` and region `13` is `188` (number of tests `1734`), and the other rows are for particular age ranges.

Does the discrepancy maybe have to do with the handling of the `cl_age90` column here? https://github.com/mcyph/covid_19_au_grab/blob/master/overseas/w_europe/fr_data/FRGovData.py

Thank you!

**Comment by mcyph** [comment]
Thank you for reporting this! This was a good catch because I doubt I would have picked this up otherwise.

Yes you're right, I was having trouble understanding the translations from Google Translate and interpreted the `cl_age90` column to mean "the number of people above age 90" when I think e.g. "09" means "ages 0-9". 

Note as you can see in the image below this data doesn't include data before mid-May. I have added some extra data from https://github.com/opencovid19-fr/data, though it's missing numbers before then and think the data from e.g. https://www.arcorama.fr/2020/05/reutiliser-les-donnees-de-notre-tableau.html could be more complete so will see if I can add it tomorrow.  

![image](https://user-images.githubusercontent.com/20507948/95336420-62f5f880-08fc-11eb-9fd8-8b7fb1f6a49c.png)

I've updated the crawler to fix this, and also fixed a couple of other issues with European data (Northern Ireland and Portugal). A few issues still remain with Kreis-level German data and it seems there's something wrong with JHU's crawler for Kosovo, among a few others. Admin1-level data for Germany should be OK though. 

Although surprising, to be honest I was under the impression there wasn't much interest in using this subnational data, and so it's become a little broken due to me not updating the crawler. I've made a lot of progress with mapping most of Europe to ISO 3166-2 codes and validating the data for obvious errors though. I'd recommend checking the live map at https://covid-19-au.com/world if you haven't seen it as it gives a good idea if the data is being properly collected. Note that some subnational sources which haven't been updated in more than 7 days such as Serbia and Turkey are excluded from that map. I think it's likely some of this subnational data isn't available anywhere else, as I'm not sure anyone else has been collecting it.

It's late in Australia but have set the data output to run. Hopefully these changes will show in the GitHub archive in around 2 hours, and will see if I can fix more remaining issues with European data tomorrow.

Please let me know if you see anything else!

- Dave Morrissey

**Comment by jad-hamza** [comment]
> Although surprising, to be honest I was under the impression there wasn't much interest in using this subnational data, and so it's become a little broken due to me not updating the crawler.

Perhaps there will be increased interest in the coming winter!

> It's late in Australia but have set the data output to run. Hopefully these changes will show in the GitHub archive in around 2 hours, and will see if I can fix more remaining issues with European data tomorrow.

Thanks a lot for the quick fix, the data for France looks good now! The map is very nice too. Do you know where I could find the population data for each `region_child` (total number of people living there)?

> Please let me know if you see anything else!

Sure!

**Comment by mcyph** [comment]
I hope so, we'll see! 

I wrote most of the below message last night though my fixed internet connection went down so couldn't finish uploading the ESRI data for France. I've finished the crawler for ESRI French data and will be able to add this as soon as my connection is restored. Unfortunately my ISP says it could take as long as the 15th October to fix this error so not sure will be able to add it till then.

I've mostly finished mapping the German Kreiss data to the GeoJSON. Most of Europe should be done now, though there are a few issues, such as when the sources themselves contain erroneous data. For example Spain has some spikes in the Bing source as you can see below. I think ultimately I should filter obviously incorrect data out, though this will take some time.

![image](https://user-images.githubusercontent.com/20507948/95448739-862db000-09af-11eb-8084-7ad77ae715c9.png)

Re population data for each `region_child`, I'm not aware of any sources which provide census-verified information on all the levels I'm providing, however I've left placeholder code in the crawler+JS visualizations for per-capita calculations. I've been thinking that rough values could be provided by the `geotiff` data at https://www.worldpop.org/ or https://dataforgood.fb.com/tools/population-density-maps/. The values could be calculated based on the polygon boundaries in the geojson files which match up with the case data schema, doing something like at this stack overflow Q+A: https://gis.stackexchange.com/questions/186483/how-to-get-the-pixels-from-a-geotiff-file-in-gdal-python-for-a-given-polygon. This might depend on my internet connection being restored but will get to it as soon as I can!

**Comment by mcyph** [comment]
Turned out just took a few hours for the internet to be restored to our area. The ESRI data is also now live on the site, though it looks identical to the sante publique data so is probably from the same source, good to know the two agree with each other anyway.

I've put together a demo script and output population by `region_child` generated from the [WorldPop data](https://www.worldpop.org/project/categories?id=3) to https://gist.github.com/mcyph/379f878dc1aae25d3b548d83309a96b6.

Most of them executed OK, though there were a few exceptions when e.g. the coordinates span one side of the globe to the other, as in the case of Antarctica. When this happened the `no_exc` column will be `False`.

I haven't taken a long look through it - I think the values typically differ from the real values, but not by orders of magnitude. I plan to add this to the properties of the GeoJSON files after normalizing them based on the expected values more.

I think this should be largely resolved so will close this issue for now but let me know if you have any comments (if you plan to make them public by all means DM me as would be very interested in the kinds of visualizations you can make with this data too!)

**Comment by jad-hamza** [comment]
> I've put together a demo script and output population by `region_child` generated from the [WorldPop data](https://www.worldpop.org/project/categories?id=3) to https://gist.github.com/mcyph/379f878dc1aae25d3b548d83309a96b6.

That's awesome, thanks!

**Comment by jad-hamza** [comment]
Reopening this to ask about this file: https://github.com/mcyph/global_subnational_covid_data/blob/3120ca02a2b6c40a64f0ca69fe0c78da3a1de486/casedata/fr/esri_france/tests_new.csv
I see many negative values there, is that an issue with the source?

**Comment by mcyph** [comment]
sorry it was a bug with combining the ESRI data on subsequent days, should be fixed now!

**Comment by jad-hamza** [comment]
looking good, thanks!
